language: node_js
node_js:
  - 4
  - 6.9.1
  - 6
  - 7.6.0
  - 7
  - node
services: redis
after_script:
  - redis-cli script flush
  - npm run ci

# Don't build pushes to branches other than master. This doesn’t affect pull-
# request builds, which are separate from branch builds in Travis.
branches:
  only:
    - master
